<a href="https://colab.research.google.com/github/Lbrb2/Aulas-Visualiza-o-e-an-lise-de-dados/blob/main/trabalho_turet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importa bibliotecas, baixa o dataset do Kaggle e carrega os dados dos livros em um DataFrame

In [ ]:
import kagglehub
import pandas as pd
import plotly.express as px


url = kagglehub.dataset_download("jealousleopard/goodreadsbooks")

df = pd.read_csv(f"{url}/books.csv", on_bad_lines="skip")

df.head()

Using Colab cache for faster access to the 'goodreadsbooks' dataset.

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

### Exibe as últimas linhas do DataFrame

In [ ]:
df.tail()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
11118,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,9781560254416,eng,512,156,20,12/21/2004,Da Capo Press
11119,45633,You Bright and Risen Angels,William T. Vollmann,4.08,0140110879,9780140110876,eng,635,783,56,12/1/1988,Penguin Books
11120,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,0140131965,9780140131963,eng,415,820,95,8/1/1993,Penguin Books
11121,45639,Poor People,William T. Vollmann,3.72,0060878827,9780060878825,eng,434,769,139,2/27/2007,Ecco
11122,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,9788497646987,spa,272,113,12,5/28/2006,Edimat Libros

### Remove as colunas do DataFrame

In [ ]:
df = df.drop(columns=['isbn', 'isbn13'])

In [ ]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'language_code',
       '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

### Exibe informações resumidas sobre o DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11123 entries, 0 to 11122
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              11123 non-null  int64
 1   title               11123 non-null  object
 2   authors             11123 non-null  object
 3   average_rating      11123 non-null  float64
 4   language_code       11123 non-null  object
 5     num_pages         11123 non-null  int64
 6   ratings_count       11123 non-null  int64
 7   text_reviews_count  11123 non-null  int64
 8   publication_date    11123 non-null  object
 9   publisher           11123 non-null  object
dtypes: float64(1), int64(4), object(5)
memory usage: 869.1+ KB

### Verifica a quantidade de valores nulos em cada coluna do DataFrame

In [ ]:
df.isnull().sum()

bookID                0
title                 0
authors               0
average_rating        0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

### Mostra estatísticas descritivas das colunas numéricas do DataFrame

In [ ]:
df.describe()

,bookID,average_rating,num_pages,ratings_count,text_reviews_count
count,11123.000000,11123.000000,11123.000000,1.112300e+04,11123.000000
mean,21310.856963,3.934075,336.405556,1.794285e+04,542.048099
std,13094.727252,0.350485,241.152626,1.124992e+05,2576.619589
min,1.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,10277.500000,3.770000,192.000000,1.040000e+02,9.000000
50%,20287.000000,3.960000,299.000000,7.450000e+02,47.000000
75%,32104.500000,4.140000,416.000000,5.000500e+03,238.000000
max,45641.000000,5.000000,6576.000000,4.597666e+06,94265.000000

### Remove os espaços das colunas e cria a coluna book_size

In [ ]:
df.rename(columns=lambda x: x.strip(), inplace=True)

df["book_size"] = pd.cut(
    df["num_pages"],
    bins=[0, 200, 400, df["num_pages"].max()],
    labels=["short", "medium", "long"])


df.head()

,bookID,title,authors,average_rating,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,book_size
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,long
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,long
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,eng,352,6333,244,11/1/2003,Scholastic,medium
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,long
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,eng,2690,41428,164,9/13/2004,Scholastic,long

### Conta quantos livros existem em cada categoria de tamanho

In [ ]:
df["book_size"].value_counts()

book_size
medium    5171
long      3003
short     2873
Name: count, dtype: int64

### Calcula a média das avaliações por categoria de tamanho de livro

In [ ]:
df.groupby("book_size")["average_rating"].mean().round(2)

/tmp/ipython-input-2264957802.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("book_size")["average_rating"].mean().round(2)

book_size
short     3.92
medium    3.89
long      4.02
Name: average_rating, dtype: float64

### Média de avaliação por tamanho de livro em gráfico de barras

In [ ]:

ratings_by_size = df.groupby("book_size", observed=True)["average_rating"].mean().round(2).reset_index()

fig = px.bar(
    ratings_by_size,
    x="book_size",
    y="average_rating",
    text="average_rating",
    color="book_size",
    color_discrete_map={"short": "skyblue", "medium": "orange", "long": "green"},
    title="Average Rating by Book Size"
)

fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig.update_layout(
    xaxis_title="Book Size",
    yaxis_title="Average Rating",
    yaxis=dict(range=[3.5, 4.2]),
    showlegend=False
)

fig.show()

###  Livros com média máxima exibidos por tamanho em gráfico de barras

In [ ]:
df_max_rating = df.query("average_rating == 5.0")


fig = px.bar(df_max_rating,
             x="book_size",
             y="average_rating",
             color="book_size",
             title="Distribution of Books with Maximum Rating by Size")

fig.show()

### Quantidade de livros por autor, título e idioma que receberam nota máxima

In [ ]:
df_max_rating[["authors","title","language_code","average_rating"]].value_counts()

authors                                               title                                                                                                                                                                language_code  average_rating
Aristophanes/F.W. Hall/W.M. Geldart                   Comoediae 1: Acharenses/Equites/Nubes/Vespae/Pax/Aves                                                                                                                grc            5.0               1
Chris    Green/Chris Wright/Paul Douglas Gardner      Fanning the Flame: Bible  Cross  and Mission                                                                                                                         eng            5.0               1
Dennis Adler/R.L. Wilson                              Winchester Shotguns                                                                                                                                                  eng            5.0               1
Elena N. Mahlow                                       Bulgakov's the Master and Margarita: The Text as a Cipher                                                                                                            eng            5.0               1
Ian        Martin/Katie Elliott                       The Complete Theory Fun Factory: Music Theory Puzzles and Games for the Early Grades                                                                                 eng            5.0               1
James E. Campbell                                     The American Campaign: U.S. Presidential Campaigns and the National Vote                                                                                             eng            5.0               1
John  Diamond                                         The Diamond Color Meditation: Color Pathway to the Soul                                                                                                              eng            5.0               1
Julie Sylvester/David Sylvester                       Willem de Kooning: Late Paintings                                                                                                                                    eng            5.0               1
Keith Donohue                                         The Irish Anatomist: A Study of Flann O'Brien                                                                                                                        eng            5.0               1
Laura Driscoll/Alisa Klayman-Grodsky/Eric     Weiner  Tyrannosaurus Wrecks (Stanley  #1)                                                                                                                                   eng            5.0               1
Middlesex Borough Heritage Committee                  Middlesex Borough (Images of America: New Jersey)                                                                                                                    eng            5.0               1
NOT A BOOK                                            The Goon Show  Volume 11: He's Fallen in the Water!                                                                                                                  eng            5.0               1
                                                      The Goon Show  Volume 4: My Knees Have Fallen Off!                                                                                                                   eng            5.0               1
Nicholas    Evans/Rhonda  Evans                       Delwau Duon: Peintiadau Nicholas Evans = Symphonies in Black: The Paintings of Nicholas Evans                                                                        wel            5.0               1
R. McL. Wilson                                        Colossians and Philemon: A Critical and Exegetical Commentary (International Critical Commentary)                                                                    eng            5.0               1
Ross Garnaut                                          Taxation of Mineral Rents                                                                                                                                            eng            5.0               1
Sara Barton-Wood                                      Bill Gates: Computer Legend (Famous Lives)                                                                                                                           eng            5.0               1
Sheri Rose Shepherd                                   His Princess Devotional: A Royal Encounter With Your King                                                                                                            eng            5.0               1
Tara MacCarthy                                        Literature Circle Guide: Bridge to Terabithia: Everything You Need For Successful Literature Circles That Get Kids Thinking  Talking  Writing—and Loving Literature  eng            5.0               1
Tim Bogenn                                            Zone of the Enders: The 2nd Runner Official Strategy Guide                                                                                                           eng            5.0               1
Todd Davis/Marc Frey                                  The New Big Book of America                                                                                                                                          eng            5.0               1
William C. Dowling                                    Oliver Wendell Holmes in Paris: Medicine  Theology  and the Autocrat of the Breakfast Table                                                                          eng            5.0               1
Name: count, dtype: int64

### Verifica se os 10 autores com mais livros tiveram algum livro com nota máxima

In [ ]:
authors_with_most_books = df["authors"].value_counts().head(10)
for autor in authors_with_most_books.keys():
    if autor in df_max_rating["authors"]:
        print(autor)

else:
    print("None of the 10 authors with the most published books received a perfect score for any of their works.")

None of the 10 authors with the most published books received a perfect score for any of their works.

### Top 10 autores com mais livros

In [ ]:
df_authors = df["authors"].value_counts().head(10).reset_index()
df_authors

                       authors  count
0                 Stephen King     40
1               P.G. Wodehouse     40
2             Rumiko Takahashi     39
3             Orson Scott Card     35
4              Agatha Christie     33
5                Piers Anthony     30
6              Mercedes Lackey     29
7                 Sandra Brown     29
8                 Dick Francis     28
9  Margaret Weis/Tracy Hickman     23

### Gráfico de barras mostrando a quantidade de livros por autor

In [ ]:
fig = px.bar(df_authors, x='count', y='authors', color='authors', title='Number of Books per Author')
fig.show()

### Gráfico de dispersão de avaliações vs. avaliações de texto por tamanho de livro

In [ ]:
fig = px.scatter(df, x='ratings_count', y='text_reviews_count', color='book_size', title='Ratings vs Text Reviews')
fig.show()

### Gráfico de caixa da distribuição das avaliações médias nos 5 idiomas mais comuns

In [ ]:
top_5_languages = df.groupby('language_code')['average_rating'].count().sort_values(ascending=False).head(5).index.tolist()

df_filtered = df[df['language_code'].isin(top_5_languages)]
fig = px.box(df_filtered, x="language_code", y="average_rating", title="Distribution of Average Ratings in the 5 Most Common Languages", color="language_code", points="all")
fig.show()

###  Barras da distribuição do tamanho dos livros nos 5 idiomas mais comuns

In [ ]:
top_5_languages = df.groupby('language_code', observed=True)['book_size'].count().sort_values(ascending=False).head(5).index.tolist()

df_filtered = df[df['language_code'].isin(top_5_languages)]
df_counts = df_filtered.groupby(['language_code', 'book_size'], observed=True).size().reset_index(name='Count')
fig = px.bar(df_counts, x="language_code", y="Count", color="book_size", title="Distribution of Book Sizes in the 5 Most Common Languages", barmode="group")

fig.show()

### Gráfico de dispersão da popularidade vs. qualidade dos livros por tamanho

In [ ]:
fig = px.scatter(df,
                 x='ratings_count',
                 y='average_rating',
                 size='text_reviews_count',
                 color='book_size',
                 title='Relationship between Popularity and Quality')
fig.show()